#_____   _                 _    _               _
#|  __ \ | |               | |  | |             | |
#| |__) || | _   _   __ _  | |__| |  __ _   ___ | | __
#|  ___/ | || | | | / _` | |  __  | / _` | / __|| |/ /
#| |     | || |_| || (_| | | |  | || (_| || (__ |   <
#|_|     |_| \__,_| \__, | |_|  |_| \__,_| \___||_|\_\
#                    __/ |
#                   |___/
#
# A JuicySeal creation
# If you need support https://discord.gg/fh7bmag9DY


# All blocks must be in there id form which can be found here: https://minecraft-ids.grahamedgecombe.com/
scaffold_block: STONE

# Negative numbers will make the hurt entity go backwards
superkb_amount: 5

# The amount of ticks (20 ticks = 1 second) that the blocks that were created for you to walk on water will last
Jesus_Block_Time: 20