#_____   _                 _    _               _
#|  __ \ | |               | |  | |             | |
#| |__) || | _   _   __ _  | |__| |  __ _   ___ | | __
#|  ___/ | || | | | / _` | |  __  | / _` | / __|| |/ /
#| |     | || |_| || (_| | | |  | || (_| || (__ |   <
#|_|     |_| \__,_| \__, | |_|  |_| \__,_| \___||_|\_\
#                    __/ |
#                   |___/
#
# A JuicySeal creation


# All blocks must be in there id form which can be found here: https://minecraft-ids.grahamedgecombe.com/
scaffold_block: STONE


# DO NOT CHANGE THE VALUES BELOW
firststart: true
sid:
logged: false
